pragma solidity ^0.5.1;

import 'zeppelin-solidity/contracts/token/ERC721/ERC721Token.sol';

contract DjtHashToken is ERC721Token("DjtHashToken", "DHT") {

    // Allow publicly creating a token with the id being autogenerated
    function create() public {
        uint256 tokenId = allTokens.length + 1;
        _mint(msg.sender, tokenId);
    }
}